## Linear Combination
### Use NumPy

$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 5 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 0 \\ 0 \\ 8 \end{bmatrix}$$
- Find <b>b</b> vector where $$b=3v_1+0v_2+0v_3$$
- Find <b>x</b> vector where $$x=-v_1+v_2-0.5v_3$$

In [2]:
import numpy as np
v1 = np.array([1,2,3])
v2 = np.array([3,5,1])
v3 = np.array([0,0,8])


b = 3*v1 + 0*v2 + 0*v3
x = -v1 + v2 -0.5*v3
print(b)
print(x)

[3 6 9]
[ 2.  3. -6.]


## Vector Span
### Use Numpy (matrix inverse) and SymPy (rref)

#### Is $$v=\begin{bmatrix} 19 \\ 10 \\ -1 \end{bmatrix}$$ in the span of 
$$v_1=\begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix},
v_2=\begin{bmatrix} -5 \\ 0 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 1 \\ 7 \\ -4 \end{bmatrix}$$

In [3]:
import sympy as sp

A = sp.Matrix([[ 3 , -5 , 1 , 19],
           [-1 , 0 , 7 , 10],
           [2 , 1 , -4 , -1]    
])
print(A.rref())

# Since it is a linear comblnation of the three vectors
# then it is in their span

(Matrix([
[1, 0, 0,  4],
[0, 1, 0, -1],
[0, 0, 1,  2]]), (0, 1, 2))


In [4]:
import numpy as np

A = np.array([[3 , -5 , 1],
              [-1 , 0 , 7],
              [2 , 1 , -4]
])

v = np.array([19, 10, -1])

x = np.linalg.inv(A)@v
print(x)
# it yields the same results found using the rref
# since the matrix has inverse and there is a solution then it is in their span

[ 4. -1.  2.]


## Vector Linear Independence
### Use rref and determinant
- Consider the following sets of vectors in R3. If the set is independent, prove it. 
- If the set is dependent, find a nontrivial linear combination of the vectors which is equal to 0.
    - {(2, 0, -3), (1, 1, 1), (1, 7, 2)}.
    - {(1, 2, -1), (4, 1, 3), (-10, 1, -11)}.

<b>Hint: we have to determine whether this implies that 𝒂=𝒃=𝒄=𝟎.</b>

In [9]:
import numpy as np
import sympy as sp

# For first set of vectors

A = np.array([[2 , 1 , 1],
              [0 , 1 , 7],
              [-3 , 1 , 2]
])
print(np.linalg.det(A))
# since the determinant is not zero then they are independant

B = sp.Matrix([[2 , 1 , 1 , 0],
              [0 , 1 , 7 , 0],
              [-3 , 1 , 2 , 0]
])
print(B.rref())
# Since all the coefficients of the three vectors are zeros then they are independant

-28.00000000000001
(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]]), (0, 1, 2))


In [19]:
# For second set of vectors

A = np.array([[1 , 4 , -10],
              [2 , 1 , 1],
              [-1 , 3 , -11]
])
print(np.linalg.det(A))

# Since determinant is zero then they are dependant

B = sp.Matrix([[1 , 4 , -10 , 0],
              [2 , 1 , 1 , 0] ,
              [-1 , 3 , -11 , 0]
])

print(B.rref())
# Using the rref we find that the first two vectors are independant thus their linear combination is equal to 0


0.0
(Matrix([
[1, 0,  2, 0],
[0, 1, -3, 0],
[0, 0,  0, 0]]), (0, 1))


## Linear Transformation
### Ex.1

$$T=\begin{bmatrix} 1&2 \\ 3&7 \end{bmatrix}$$
- Write the linear transformation expression of this matrix. i.e. Linear functions of x,y. 
- Apply the transformation matrix <b>T</b> to the following vectors:
$$\begin{bmatrix} 1 \\ 0 \end{bmatrix},\begin{bmatrix} 0 \\ 1 \end{bmatrix} $$
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(1,0)</b>

In [20]:
'''
[[1  , 2],[3 , 7]] * [ x, y]
'''
T = np.array([[ 1, 2],
              [3 , 7]
])

e1 = np.array([1 , 0])
e2 = np.array([0 , 1])

print(T@e1)
print(T@e2)


[1 3]
[2 7]


### Ex.2
### For the expression $$T\begin{bmatrix} x \\ y \end{bmatrix}=\begin{bmatrix} x+y \\ y \end{bmatrix}$$
- Find the transformation matrix.
- Represent the transformation graphically <b>(on paper)</b>.
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(3,4)</b>

In [21]:
T = np.array([[1 , 1],
              [0 , 1]
])
print(np.linalg.inv(T)@np.array([3,4]))

[-1.  4.]


## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [22]:
A = np.array([[3 , 8],
              [4 , 6]
])

B = np.array([[4 , 6],
              [3 , 8]
])

C = np.array([ [ 6 , 1 , 1],
              [4 , -2 , 5],
              [2 , 8 , 7]
])

D = np.array([[3 , 2 , 0 , 1],
              [4 , 0 , 1 , 2],
              [3 , 0 , 2 , 1],
              [9 , 2 , 3 , 1]
])
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(C))
print(np.linalg.det(D))

-14.000000000000004
14.000000000000004
-306.0
24.000000000000004


## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [30]:
X = sp.Matrix([[1 , 2 , 4 , 4],
               [3 , 4 , 8 , 0]
])

Y = sp.Matrix([[1 , 2 , 3],
               [2 , 3 , 5],
               [3 , 4 , 7],
               [4 , 5 , 9]
])
print(X.rref())
print(Y.rref())
# Both matrices have rank of 2

(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))
(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))


In [33]:
X = np.array([[1 , 2 , 4 , 4],
               [3 , 4 , 8 , 0]
])
print(np.linalg.matrix_rank(X))
Y = np.array([[1 , 2 , 3],
               [2 , 3 , 5],
               [3 , 4 , 7],
               [4 , 5 , 9]
])
print(np.linalg.matrix_rank(Y))

2
2


## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [35]:
A = np.array([[3 , 8],
              [4 , 6]
])

B = np.array([[4 , 6],
              [3 , 8]
])

C = np.array([ [ 6 , 1 , 1],
              [4 , -2 , 5],
              [2 , 8 , 7]
])

D = np.array([[3 , 2 , 0 , 1],
              [4 , 0 , 1 , 2],
              [3 , 0 , 2 , 1],
              [9 , 2 , 3 , 1]
])
print(np.linalg.inv(A))
print()
print(np.linalg.inv(B))
print()
print(np.linalg.inv(C))
print()
print(np.linalg.inv(D))

[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

[[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

[[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]
