In [26]:
import numpy as np

### Practice some NumPy commands:
- Create 3 * 3 array.
- Check its shape.
- Select first row.
- Select 2nd column.
- Select the 2nd element in the third column.
- Create 2*2 from the first two elements of the first 2 rows and columns.
- Create single row vector.
- Create single column vector.

In [27]:
A = np.array([[1 , 2 , 3],
              [1 , 2 , 3],
              [1 , 2 , 3]
])
print(A)
print("Shape: ")
print(A.shape)

print()
print("First row:")
print(A[0])

print()
print("second column")
print(A[:,1])

print()
print("second element in third column:")
print(A[1,2])

print()
B = A[:2,:2]
print(B)

print()
single_row = np.array([1,2,2]).reshape(1,3)
print(single_row.shape)

print()
single_col = np.array([1,2,2]).reshape(3,1)
print(single_col.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape: 
(3, 3)

First row:
[1 2 3]

second column
[2 2 2]

second element in third column:
3

[[1 2]
 [1 2]]

(1, 3)

(3, 1)


## System of linear equations:
- The following system of linear equations can be represented as <b>Ax=b</b>.
- Define matrix <b>A</b> and vector <b>b</b> as numpy arrays.
- Print them out.
1. $$3x-y=2$$ $$x=4 $$
$$$$
2. $$3x-2y=7$$  $$2x-2y=2$$
$$$$
3. $$2x-2y+z=7$$  $$x+y+z=2$$  $$3x-2y-z=3$$ 

In [2]:
import numpy as np
A1 = np.array([[3 , -1],
              [1 , 0]
])
B1 = np.array([[2] , 
               [4]])



A2 = np.array([[3 , -2],
              [2 , -2]
])

B2 = np.array([7 , 2])



A3 = np.array([[2 , -2 , 1],
               [1 , 1 , 1],
               [3 , -2 , -1]
])
B3 = np.array([7 , 2 , 3])

### Find a solution for the above systems of equations using:
<b>np.linalg.inv()</b>

In [29]:
X1 = np.linalg.inv(A1)@B1
print(X1)

X2 = np.linalg.inv(A2)@B2
print(X2)

X3 = np.linalg.inv(A3)@B3
print(X3)

[ 4. 10.]
[5. 4.]
[ 0.90909091 -1.36363636  2.45454545]


In [ ]:
pip install sympy

In [11]:
import sympy as sp

A  = sp.Matrix([3 , -1 , 2],
              [1 , 0 , 4])

print(A.rref())

ModuleNotFoundError: No module named 'sympy'

### Find a solution for the above systems of equations using:
<b>np.linalg.solve()</b>

In [21]:
print(np.linalg.solve(A1,B1))
print(np.linalg.solve(A2,B2))
print(np.linalg.solve(A3,B3))

[ 4. 10.]
[5. 4.]
[ 0.90909091 -1.36363636  2.45454545]


## Using numpy arrays
- For the above systems of equations, multiply matrix <b>A</b> and vector <b>x</b> and make sure the result is <b>b</b>.

In [30]:
print(np.matmul(A1,X1))
print(B1)

[2. 4.]
[2 4]


In [32]:
print(np.matmul(A2,X2))
print(B2)

[7. 2.]
[7 2]


In [33]:
print(np.matmul(A3,X3))
print(B3)

[7. 2. 3.]
[7 2 3]


## Vector Norms

*italicised text*### Calculate in paper then confirm your results using numpy linalg.norm().
- Calculate L1, L2, Lmax norms for the following vectors:
$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 3 \\ 1 \\ 3 \end{bmatrix}$$
- Calculate L3 norm for the vector
$$v_3=\begin{bmatrix} 2 \\  3 \\ 4 \end{bmatrix}$$

In [35]:
v1 = np.array([1 , 2 , 3])
v2 = np.array([3 , 3 , 1 , 3])

print("For vector v1:")
for i in range(1,3):
  print("L",i," Norm: ", np.linalg.norm(v1,i))
print("L max Norm: ", np.linalg.norm(v1,np.inf))

print()
print("For vector v2:")
for i in range(1,3):
  print("L",i," Norm: ", np.linalg.norm(v2,i))
print("L max Norm: ", np.linalg.norm(v2,np.inf))

For vector v1:
L 1  Norm:  6.0
L 2  Norm:  3.7416573867739413
L max Norm:  3.0

For vector v2:
L 1  Norm:  10.0
L 2  Norm:  5.291502622129181
L max Norm:  3.0


In [37]:
v3 = np.array([2 , 3 , 4])
print(np.linalg.norm(v3,3))

4.626065009182741


## Calculate using numpy only.
### Calculate L1, L2, L3, and Lmax for the following vectors:
$$v_1=\begin{bmatrix} 5 \\ 6 \end{bmatrix},
v_2=\begin{bmatrix} 4 \\ 3 \\ 2 \end{bmatrix},
v_3=\begin{bmatrix} 4 \\ 3 \\ 2 \\ 8 \\ 9 \end{bmatrix}$$

In [39]:
v1 = np.array([5 , 6])
v2 = np.array([4 , 3 , 2])
v3 = np.array([4 , 3 , 2 , 8 , 9])
vectors = [v1,v2,v3]

for i in range(3):
  print()
  print("For vector v",i+1,":")
  for j in range(1,4):
    print("L",j," Norm: ",np.linalg.norm(vectors[i],j))
  print("L max Norm: ",np.linalg.norm(vectors[i],j))


For vector v 1 :
L 1  Norm:  11.0
L 2  Norm:  7.810249675906654
L 3  Norm:  6.986368027818105
L max Norm:  6.986368027818105

For vector v 2 :
L 1  Norm:  9.0
L 2  Norm:  5.385164807134504
L 3  Norm:  4.626065009182741
L max Norm:  4.626065009182741

For vector v 3 :
L 1  Norm:  26.0
L 2  Norm:  13.19090595827292
L 3  Norm:  11.02473771449733
L max Norm:  11.02473771449733


## Dot Product

[link text](https:// [link text](https://))### Calculate in paper then confirm your results using numpy.
#### Calculate the dot product of the following vectors:
$$v_1=\begin{bmatrix} 2 \\ -1 \\ 5 \\ 0 \end{bmatrix} and
v_2=\begin{bmatrix} 4 \\ -3 \\ 1 \\ -1 \end{bmatrix}$$
#### Calculate the dot product of the following vectors and explain the result:
$$v_1=\begin{bmatrix} 3 \\ 2 \\ -1 \\ 4 \end{bmatrix} and
v_2=\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix} $$ 

In [40]:
v1 = np.array([2 , -1 , 5 , 0])
v2 = np.array([4 , -3 , 1 , -1])
print(np.dot(v1,v2))

16


In [45]:
v1 = np.array([3 , 2 , -1 , 4])
v2 = np.array([1 , -1 , 1 , 0])
print(np.dot(v1,v2))

0


## Calculate in paper then confirm your results using numpy.
### Create two vectors in 2, 3, and 4 dimensions.
### Perform vector addition, subtraction, and dot product of these vectors.

In [46]:
a = np.array([1 , 2])
b = np.array([ 3 , 4])

print(a+b)
print(a-b)
print(np.dot(a,b))


a = np.array([1 , 2 , 3 ])
b = np.array([ 4 , 5 , 6])

print(a+b)
print(a-b)
print(np.dot(a,b))

a = np.array([ 1, 2 , 3 , 4])
b = np.array([3 , 4 , 5 , 6])

print(a+b)
print(a-b)
print(np.dot(a,b))

[4 6]
[-2 -2]
11
[5 7 9]
[-3 -3 -3]
32
[ 4  6  8 10]
[-2 -2 -2 -2]
50


## Matrix Operations

## Calculate in paper then confirm your results using numpy.
### Matrix Multiplication AB then Transpose the result.
$$A=\begin{bmatrix} 3&1&0 \\ 2&1&2 \end{bmatrix}, B=\begin{bmatrix} 1&3 \\ 2&5 \\ -1&3 \end{bmatrix}$$
$$A=\begin{bmatrix} 1&0&3 \\ 4&5&-1 \\ 0&0&2  \end{bmatrix}, B=\begin{bmatrix} 1\\2\\5 \end{bmatrix}$$

In [48]:
A = np.array([[3,1,0],
              [2,1,2]
])

B = np.array([[1,2],
              [2,5],
              [-1,3]
])

print(np.matmul(A,B).T)


A = np.array([[1,0,3],
              [4,5,-1],
              [0,0,2]
])

B = np.array([1,2,5])

print(np.matmul(A,B).T)

[[ 5  2]
 [11 15]]
[16  9 10]


## Different Types of Matrices
### Create 3 by 3 and 4 by 4 identity matrices 

In [49]:
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
mat = np.eye(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Create a diagonal matrix contains [2,4,5,11] numbers in its diagonal.

In [55]:
A = np.diag([2,4,5,11])
print(A)

[[ 2  0  0  0]
 [ 0  4  0  0]
 [ 0  0  5  0]
 [ 0  0  0 11]]


### Create a 5 by 5 scalar matrix of number 7

In [56]:
print(7*np.eye(5))

[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]


### Using SymPy get the rref of the following matrices

In [58]:
import sympy as sp

A = sp.Matrix([[1,0,1,3],
               [2,3,4,7],
               [-1,-3,-3,-4]
])
A.rref()

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]), (0, 1))

In [60]:
A = sp.Matrix([[1,1,1],
               [1,2,2],
               [1,2,3]
])

A.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [61]:
A = sp.Matrix([[1,2,3],
               [2,-1,1],
               [3,0,-1]
])
A.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

#### Find the solution of the following system of linear equation using SymPy Matrix rref()

1. $$x+y+z=6$$  $$x+2y+2z=9$$  $$x+2y+3z=10$$ 
$$$$
2. $$x+2y+3z=9$$  $$2x-y+z=8$$  $$3x-z=3$$ 

In [63]:
A = sp.Matrix([[1,1,1,6],
               [1,2,2,9],
               [1,2,3,10]
])

A.rref()
#z = 1
#y = 2
#x = 3

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]), (0, 1, 2))

In [64]:
A = sp.Matrix([[1,2,3,9],
               [2,-1,1,8],
               [3,0,-1,3]
])
A.rref()
#z = 3
#y = -1
#x = 2

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]), (0, 1, 2))

#### Find the solution of the following system of linear equation 
- Using SymPy Matrix rref()

1. $$x-2y=1$$ $$3x-6y=11 $$
$$$$
2. $$x-2y=1$$ $$3x-6y=3 $$
$$$$
3. $$x+2y+3z=6$$  $$2x+5y+2z=4$$  $$6x-3y+z=2$$ 
$$$$
4. $$2x+4y-2z=2$$  $$4x+9y-3z=8$$  $$-2x-3y+7z=10$$ 

1

In [65]:
A = sp.Matrix([[1,-2,1],
               [3,-6,11]
])
A.rref()
# No solution

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]), (0, 2))

2

In [66]:
A = sp.Matrix([[1,-2,1],
               [3,-6,3]
])
A.rref()
#inf number of solutions

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]), (0,))

In [67]:
A = sp.Matrix([[1,2,3,6],
               [2,5,2,4],
               [6,-3,1,2]
])
A.rref()
#z = 2
#y = 0
#x = 0

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]), (0, 1, 2))

In [68]:
A = sp.Matrix([[2,4,-2,2],
               [4,9,-3,8],
               [-2,-3,7,10]
])
A.rref()
#z = 2
#y = 2
#x = -1

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]), (0, 1, 2))